Add Ruby environment check in redcarpet.rb
I use the Homebrew version of Ruby (currently 4.0.6), which is set with the `TM_RUBY` TextMate variable as `/opt/homebrew/bin/ruby`. Initially when trying to preview GitHub-flavoured Markdown files with TextMate, the preview window would show the following error:

```
undefined method 'parse' for class CGI (NoMethodError)
```

Finally, after a (very) long back and forth with ChatGPT, where the crux of the matter was that the bundle was using its own Ruby version 2.6 and wasn't using the TextMate-set Ruby, I found out I had to add this code at the top of `redcarpet.rb` at `'~/Library/Application Support/TextMate/Bundles/Markdown (GitHub).tmbundle/Support/bin/redcarpet.rb'`

```
require "rbconfig"

if ENV["TM_RUBY"] &&
   File.executable?(ENV["TM_RUBY"]) &&
   File.realpath(RbConfig.ruby) != File.realpath(ENV["TM_RUBY"])
  exec ENV["TM_RUBY"], __FILE__, *ARGV
end

# puts RUBY_VERSION
# puts RbConfig.ruby
# puts "TM_RUBY=#{ENV["TM_RUBY"].inspect}"
# exit

require "rubygems"
gem "cgi"
require "cgi"
```
The commented-out part was used to test Ruby versions. I had some version dependency issues for `bundler` and Ruby, which I managed to solve updating my gems using `gem update --system`.

Has anybody had a similar issue? Can anybody test this code?